dataset_name: fin_text
train:
  file_path: /content/drive/MyDrive/FSA/data/train.csv
  tokenizer_name: bert-base-uncased
test:
  file_path: /content/drive/MyDrive/FSA/data/test.csv
  tokenizer_name: bert-base-uncased
