dataset_name: fin_text
train:
  file_path: ../data/sentiment_analysis/train.csv
  tokenizer_name: bert-large-uncased
test:
  file_path: ../data/sentiment_analysis/test.csv
  tokenizer_name: bert-large-uncased
